---
abstract: ~
author:
  - 'Michael Stapelberg, C<< <michael at stapelberg.de> >>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AllKnowingDNS
no_index:
  directory:
    - inc
    - t
requires:
  Mouse: 0
  MouseX::NativeTraits: 0
  Net::DNS: 0
  NetAddr::IP: 0
  Privileges::Drop: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.3
